# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
#version: '3.8'
networks:
  backend:
    name: demo
    driver: bridge
volumes:
  demo_postgres_data:
    driver: local
# Define services
services:
  # App backend service
  app:
    image: demo-app:latest
    build:
      context: ./
      dockerfile: "Dockerfile"
      # Give the container the name web-app. You can changes to something else.
    container_name: web-app
    # Forward the exposed port 8080 on the container to port 8080 on the host machine
    ports:
      - "8888:8888"
    networks:
      - backend
    # This service depends on postgres. Start that first.
    depends_on:
      - db
    healthcheck:
      test: curl --fail http://app:8888/actuator/health
      interval: 1m
      timeout: 10s
      retries: 5
  # Database Service (Postgres)
  db:

    image: mysql:8.0
    container_name: mysql-db
    restart: always

    volumes:
      - demo_mysql_data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3307:3306"
    # Setup the username, password, and database name. You can changes these values.
    environment:
      - "MYSQL_DATABASE=employee"
      - "MYSQL_USER=mysqluser"
      - "MYSQL_PASSWORD=mysqlpassword"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -u $${MYSQL_USER} -p$${MYSQL_PASSWORD}" ]
      interval: 1m
      timeout: 10s
      retries: 5

